### PR TITLE
matter.js boilerplate

### PR DESCRIPTION
**Pull request by phrabos**
matter.js sandbox template renders canvas on interactive shapes on soloPage

### CODE REVIEW

**Review by glass-waves — APPROVED** [review]

**Review by Anthony-Rosario — APPROVED** [review]

**Comment by stephen-leisy** [comment]
im all abount this.

**Review by kat-sauma — APPROVED** [review]
nice use of useRef!

**Review by Tylerpfarris — APPROVED** [review]
pull request more like GOOD JOB

**Review by jakethrasher — COMMENTED** [review]
looks great!

**Review by erichsauer — APPROVED** [review]
This is what progress looks like!

**Pull request merged**
